version: '3'
services:
  this-app:
    image: rcjmedia/my-gallery:${IMAGE_VERSION}-local
    command: ["./node_modules/.bin/nodemon", "server.js"]
    container_name: my-gallery
    volumes:
      - ".:/app/:rw"
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "${EXPRESS_HOST_PORT}:${EXPRESS_CONTAINER_PORT}"
    networks:
      - this-app-network
  db: 
    image: postgres:10.0-alpine
    env_file: .env
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    networks:
      - this-app-network
volumes:
    pg-data-volume:
networks:
  this-app-network: