
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users_table').del()
    .then(function () {
      // Inserts seed entries
      return knex('users_table').insert([
        {
          username: 'johndoe',
          password: 'johndoe',
          userlevel: 'admin',
          firstname: 'John',
          lastname: 'Doe',
          email: 'john@doe.com',
          phone:'(808) 000-1100',
          address1: '100 Outofnowhere Street',
          address2: '',
          city: 'Honolulu',
          state: 'Hawaii',
          zipcode: '96819',
          country: 'United States',
          timezone: 'HST',
          avatar_url: '/myavatar.jpg',
          sex: 'Male',
          profile_url: '/johndoe',
          motto: 'Try and try until you die.',
          interests: 'Basketball, fishing, roadtrips',
          website: 'ohanadaily.com',
          linkedin: 'https://www.linkedin.com/in/jeffweiner08/',
          facebook: 'https://www.facebook.com/jeff.weiner.7',
          twitter: 'https://twitter.com/jeffweiner',
          instagram: 'https://www.instagram.com/jeff_weiner/',
          youtube: 'https://www.youtube.com/user/techcrunch'
        },
        {
          username: 'user1',
          password: 'user1',
          userlevel: 'subscriber',
          firstname: 'User',
          lastname: 'One',
          email: 'one@user.com',
          phone:'(808) 000-1100',
          address1: '100 Outofnowhere Street',
          address2: '',
          city: 'Honolulu',
          state: 'Hawaii',
          zipcode: '96819',
          country: 'United States',
          timezone: 'HST',
          avatar_url: '/user1.jpg',
          sex: 'Male',
          profile_url: '/user1',
          motto: 'Try and try until you die.',
          interests: 'Basketball, fishing, roadtrips',
          website: 'ohanadaily.com',
          linkedin: 'https://www.linkedin.com/in/jeffweiner08/',
          facebook: 'https://www.facebook.com/jeff.weiner.7',
          twitter: 'https://twitter.com/jeffweiner',
          instagram: 'https://www.instagram.com/jeff_weiner/',
          youtube: 'https://www.youtube.com/user/techcrunch'
        },
        {
          username: 'twouser',
          password: 'twouser',
          userlevel: 'subscriber',
          firstname: 'Two',
          lastname: 'User',
          email: 'two@user.com',
          phone:'(808) 000-1100',
          address1: '100 Outofnowhere Street',
          address2: '',
          city: 'Honolulu',
          state: 'Hawaii',
          zipcode: '96819',
          country: 'United States',
          timezone: 'HST',
          avatar_url: '/twouser.jpg',
          sex: 'Female',
          profile_url: '/twouser',
          motto: 'Try and try until you die.',
          interests: 'Basketball, fishing, roadtrips',
          website: 'ohanadaily.com',
          linkedin: 'https://www.linkedin.com/in/jeffweiner08/',
          facebook: 'https://www.facebook.com/jeff.weiner.7',
          twitter: 'https://twitter.com/jeffweiner',
          instagram: 'https://www.instagram.com/jeff_weiner/',
          youtube: 'https://www.youtube.com/user/techcrunch'
        },
        {
          username: 'threeuser',
          password: 'threeuser',
          userlevel: 'subscriber',
          firstname: 'Three',
          lastname: 'User',
          email: 'three@user.com',
          phone:'(808) 000-1100',
          address1: '100 Outofnowhere Street',
          address2: '',
          city: 'Honolulu',
          state: 'Hawaii',
          zipcode: '96819',
          country: 'United States',
          timezone: 'HST',
          avatar_url: '/threeuser.jpg',
          sex: 'Male',
          profile_url: '/threeuser',
          motto: 'Try and try until you die.',
          interests: 'Basketball, fishing, roadtrips',
          website: 'ohanadaily.com',
          linkedin: 'https://www.linkedin.com/in/jeffweiner08/',
          facebook: 'https://www.facebook.com/jeff.weiner.7',
          twitter: 'https://twitter.com/jeffweiner',
          instagram: 'https://www.instagram.com/jeff_weiner/',
          youtube: 'https://www.youtube.com/user/techcrunch'
        },
        {
          username: 'fouruser',
          password: 'fouruser',
          userlevel: 'subscriber',
          firstname: 'Four',
          lastname: 'User',
          email: 'four@user.com',
          phone:'(808) 000-1100',
          address1: '100 Outofnowhere Street',
          address2: '',
          city: 'Honolulu',
          state: 'Hawaii',
          zipcode: '96819',
          country: 'United States',
          timezone: 'HST',
          avatar_url: '/fouruser.jpg',
          sex: 'Male',
          profile_url: '/fouruser',
          motto: 'Try and try until you die.',
          interests: 'Basketball, fishing, roadtrips',
          website: 'ohanadaily.com',
          linkedin: 'https://www.linkedin.com/in/jeffweiner08/',
          facebook: 'https://www.facebook.com/jeff.weiner.7',
          twitter: 'https://twitter.com/jeffweiner',
          instagram: 'https://www.instagram.com/jeff_weiner/',
          youtube: 'https://www.youtube.com/user/techcrunch'
        }
      ]);
    });
};
